# should the plugin open the fare gate when someone forgets to tap in/out?
open-on-penalty: true

# penalty amount when someone did not tap in/out
penalty: 8.0

# new card deposit
deposit: 5.0

# minimum amount that a card can have to enter the network.
min-amount: 3.0

# prices listed when buying a new Iciwi card
price-array: [10.0, 20.0, 30.0, 50.0, 100.0]

# database
database: jdbc:sqlite:IciwiCards.db

# max time allowed for transfer
max-transfer-time: 300000

# time to wait until a fare gate closes, in ticks
gate-close-delay: 100

# time to wait until a fare gate closes after a player walks through, in ticks
close-after-pass: 5

# should the plugin require validated paper tickets?
require-entry-punch: false

# the following options pertain to new stations
# default operator's name
default-operator: ExampleOperator

# default station for new journeys
default-end-station: ExampleStation

# default train class. An underscore prefix makes the train class only accessible by card
default-class: _Second

# default ticket price. Used when creating a new fare
default-ticket-price: 5.0

# glass fare gate speed
ticks-to-open: 20
ticks-to-close: 20

# custom item usage
card:
  material: NAME_TAG
  custom-model-data: 0

ticket:
  material: PAPER
  custom-model-data: 0

railpass:
  material: FILLED_MAP
  custom-model-data: 0
  
# usage passwords
a: password
b: password
c: password
d: password
